image: golang:1.9

variables:
  REPO_NAME: gitlab.ie.u-ryukyu.ac.jp/e205743/e205743-filewrite

# Define a yaml template for running a build and then running your tests
stages:
  - build
  - test

build-project:
  stage: build
  script:
    - golang --version
    - golang build
    - golang test --verbose
  coverage: '/coverage: \d+\.\d+% of statements/'